name: e2ee_device_binding_demo_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  kms_e2ee_package:
    path: ../sdk/kms_e2ee_package
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  dio: ^5.2.1
  local_auth: ^2.3.0
  win32: ^5.13.0
  mobile_scanner: ^5.1.1
  x509: ^0.2.4+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/keycloak-server.pem

